#!/bin/bash
set -u -o pipefail -o noclobber

function print_help() {
cat <<END_HELP
 All our commands gathered together so we don't forget them.
 This gathers them hierarchically, check out each subcommand.

 All subcommands are "mandatory" in the sense that if they are not specified,
 this script will ask for them one by one. So not even required to remember
 the subcommands for this command!

 Subcommands:
   dev               All the local dev commands
   stack             Working with the "real" services/containers
   test              Running tests
   worker            Working with the short-lived scripts/containers

 Each subcommand has its own '--help' command.
END_HELP
}

function print_dev_help() {
cat <<END_HELP
 All the dev commands for frontend and backend together.

 Subcommands:
   format  [both|frontend|backend]
   install [both|frontend|backend]
   run               Only runs frontend (run backend in docker with 'stack')

 Examples:
  ./devx dev format both
  ./devx dev install backend
  ./devx dev run
END_HELP
}

function print_stack_help() {
cat <<END_HELP
 Interact with the main containers (frontend, backend, database, proxy).

 Subcommands:
   up [build]                   Spin up the containers
   down [remove]                Spin down the containers
   logs [follow] [<service>]    Show the logs for the containers

 The [build], [remove] and [follow] are arguments, where each is a yes/no
 but can also use their name (like 'build' or 'no-build').
 For the logs-service, use one of these:
   all, backend, frontend, database, proxy, sync_worker

 Examples:
  ./devx stack up build
  ./devx stack down no-remove
  ./devx stack logs no backend
END_HELP
}

function print_test_help() {
cat <<END_HELP
 Run tests!

 Subcommands:
   backend [normal|coverage|ci]    Run the backend tests
   frontend                        Run the frontend tests

 The 'backend coverage' will try to open the generated html page with
 'xdg-open'.

 Examples:
   ./devx test backend coverage
   ./devx test backend ci
   ./devx test frontend
END_HELP
}

function print_worker_help() {
cat <<END_HELP
 Run a worker.

 Subcommands:
   sync [build]         Run the sync worker once
   csv                  Run the csv worker once (always builds first)

 The [build] is an argument that accepts yes or no, but can also use their name
 (like 'build' or 'no-build').

 Examples:
   ./devx worker sync no-build
   ./devx worker csv yes
END_HELP
}

# Navigate to the root directory
git_root=$(git rev-parse --show-toplevel 2>/dev/null)
if [[ -z "$git_root" ]]; then
	echo "Not in a git repository, aborting." >&2
	exit 1
fi

cd "$git_root" || exit 1

# Source the necessary files
source ".env"
venv_file=$(find ./backend -wholename "*bin/activate" | head -n1)
if [[ -z "$venv_file" ]]; then
	echo "No venv-activate file found under 'backend/', exiting." >&2
	exit 2
fi
# Disable shellcheck for a 'source-file' it does not know:
# shellcheck source=/dev/null
source "$venv_file"


# Helper function to select one thing from options
choose_return=""
function choose() {
	local prompt="$1";
	shift
	local options=("$@")

	echo ""             # Newline before prompt
	echo "$prompt"
	PS3="Select a number: "
	select opt in "${options[@]}"; do
		if [[ -n "$opt" ]]; then
			choose_return="$opt"
			break
		else
			echo "Invalid choice, try again."
		fi
	done
}

function run() {
	echo "[CMD] $*"
	eval "$*"
}

function contains() {
	element="$1"
	shift

	[[ -z "$element" ]] && return 1

	for e in "$@"; do
		[[ "$e" == "$element" ]] && return 0
	done
	return 1
}

yes_no_return=""
function yes_no() {
	local input="$1"
	local question="$2"
	local prompt="$3"

	case "$input" in
		"$question")
			yes_no_return="yes"
			;;
		"no-${question}")
			yes_no_return="no"
			;;
		yes|no)
			yes_no_return="$input"
			;;
		*)
			choose "$prompt" yes no
			yes_no_return="$choose_return"
			;;
	esac
}


# Dev subcommand
function dev() {
	local action="${1:-}"
	if [[ "$action" == --help || "$action" == -h ]]; then
		print_dev_help
		exit 0
	fi

	local actions=(format install run)
	if ! contains "$action" "${actions[@]}"; then
		choose "Dev action?" "${actions[@]}"
		action="$choose_return"
	fi

	# Target is for all but 'run'
	local target="${2:-}"
	local targets=(both frontend backend)
	if ! [[ "$action" == run ]]; then
		if ! contains "$target" "${targets[@]}"; then
			choose "Dev ${action} target?" "${targets[@]}"
			target="$choose_return"
		fi
	fi

	case "$action" in
		format)
			if [[ "$target" == backend || "$target" == both ]]; then
				(run cd backend && run ruff check --fix && run ruff format)
			fi
			if [[ "$target" == frontend || "$target" == both ]]; then
				(
					run cd frontend \
					&& run npm run format \
					&& run npm run lint \
					&& run npm run typecheck
				)
			fi
			;;
		install)
			if [[ "$target" == backend || "$target" == both ]]; then
				(run cd backend && run pip install -r requirements-dev.txt)
			fi
			if [[ "$target" == frontend || "$target" == both ]]; then
				(run cd frontend && run npm ci)
			fi
			;;
		run)
			(run cd frontend && run npm run dev)
			;;
	esac
}


# Stack subcommand
function stack() {
	local action="${1:-}"
	if [[ "$action" == --help || "$action" == -h ]]; then
		print_stack_help
		exit 0
	fi

	local actions=(up down logs)
	if ! contains "$action" "${actions[@]}"; then
		choose "Stack action?" "${actions[@]}"
		action="$choose_return"
	fi

	case "$action" in
		up)
			local mode="${2:-}"
			yes_no "$mode" build "Build before starting?"
			mode="$yes_no_return"

			if [[ "$mode" == "yes" ]]; then
				run docker compose up --build --wait -d
			else
				run docker compose up -d
			fi
			;;
		down)
			local wipe="${2:-}"
			yes_no "$wipe" remove "Remove volumes?"
			wipe="$yes_no_return"

			if [[ "$wipe" == "yes" ]]; then
				run docker compose down -v
			else
				run docker compose down
			fi
			;;
		logs)
			local follow="${2:-}"
			local service="${3:-}"

			yes_no "$follow" follow "Follow logs?"
			follow="$yes_no_return"

			local services=(all backend frontend database proxy sync_worker)
			# If requested service is not in available services, ask
			if ! contains "$service" "${services[@]}"; then
				choose "Service?" "${services[@]}"
				service="$choose_return"
			fi

			cmd="docker compose logs"
			[[ "$follow" == "yes" ]] && cmd="$cmd -f"
			[[ "$service" != "all" ]] && cmd="$cmd $service"

			run "$cmd"
			;;
	esac
}

# Test subcommand
function test_cmd() {
	local target="${1:-}"
	if [[ "$target" == --help || "$target" == -h ]]; then
		print_test_help
		exit 0
	fi

	local targets=(both backend frontend)
	if ! contains "$target" "${targets[@]}"; then
		choose "Test target?" "${targets[@]}"
		target="$choose_return"
	fi

	if [[ "$target" == backend || "$target" == both ]]; then
		local mode="${2:-}"
		local modes=(normal coverage ci)
		if ! contains "$mode" "${modes[@]}"; then
			choose "Backend test mode?" "${modes[@]}"
			mode="$choose_return"
		fi

		case "$mode" in
			normal)
				# Run in (subshell) so that the 'cd' does not persist
				(run cd backend && run pytest)
				;;
			coverage)
				(
					run cd backend \
						&& run coverage run -m pytest \
						&& run coverage html \
						&& run xdg-open htmlcov/index.html >/dev/null 2>&1
				)
				;;
			ci)
				run docker compose -f docker-compose.ci.yml \
					--project-name viernulvier-ci \
					exec -T backend pytest tests/
				;;
			esac
	fi
	if [[ "$target" == frontend || "$target" == both ]]; then
		(run cd frontend && run npm test)
	fi
}

# Worker subcommand
function worker() {
	local type="${1:-}"
	if [[ "$type" == --help || "$type" == -h ]]; then
		print_worker_help
		exit 0
	fi

	local types=(sync csv)
	if ! contains "$type" "${types[@]}" ; then
		choose "Worker?" "${types[@]}"
		type="$choose_return"
	fi

	case "$type" in
		sync)
			local mode="${2:-}"
			yes_no "$mode" build "Build before syncing?"
			mode="$yes_no_return"

			if [[ "$mode" == "yes" ]]; then
				run docker compose --profile sync build
			fi
			run docker compose --profile sync run --rm sync_worker
			;;
		csv)
			run docker compose up --build
			run docker compose --profile csv build
			run docker compose --profile csv run --rm csv_worker
			;;
	esac
}

# Main entrypoint
main() {
	local cmd="${1:-}"
	if [[ "$cmd" == --help || "$cmd" == -h ]]; then
		print_help
		exit 0
	fi

	local cmds=(dev stack test worker)
	if ! contains "$cmd" "${cmds[@]}"; then
		choose "What do you want to do?" "${cmds[@]}"
		cmd="$choose_return"
	fi

	case "$cmd" in
		dev) shift; dev "$@" ;;
		stack) shift; stack "$@" ;;
		test) shift; test_cmd "$@" ;;
		worker) shift; worker "$@" ;;
		*)
			echo "Unknown command: $cmd" >&2
			print_help
			exit 1
			;;
	esac
}

main "$@"
