services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.ci # separate dockerfile because of ssl certs
    # No ports exposed for CI to avoid conflicts
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - default

  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - default

  backend:
    build:
      context: ./backend
      target: test
    expose:
      - "8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      VIERNULVIER_KEY: ${VIERNULVIER_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES}
      TEST_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
