services:
  postgres:
    image: postgres:16
    container_name: database_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: viernulvier
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./database/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql # Run schema automatically on first startup

volumes:
  postgres_data: