name: Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: self-hosted

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Build and Restart Containers
        run: |
          docker-compose up --build -d --remove-orphans

      - name: System Cleanup
        if: always()
        run: |
          docker image prune -f